# Auto-generated Chinese name mapping for 58 destinations
CN_NAMES = {
    "Sanya": "三亚",
    "Qingdao": "青岛",
    "Xiamen": "厦门",
    "Beihai/Weizhou Island": "北海/涠洲岛",
    "Zhuhai": "珠海",
    "Jeju Island (South Korea)": "济州岛（韩国）",
    "Phuket (Thailand)": "普吉岛（泰国）",
    "Krabi (Thailand)": "甲米（泰国）",
    "Bali (Indonesia)": "巴厘岛（印尼）",
    "Nha Trang (Vietnam)": "芽庄（越南）",
    "Boracay (Philippines)": "长滩岛（菲律宾）",
    "Maldives": "马尔代夫",
    "Zhangjiajie": "张家界",
    "Guilin/Yangshuo": "桂林/阳朔",
    "Guizhou (Libo/Miao Village)": "贵州（荔波/苗寨）",
    "Daocheng Yading (Sichuan)": "稻城亚丁（四川）",
    "Changbai Mountain": "长白山",
    "Lhasa (Tibet)": "拉萨（西藏）",
    "Hulunbuir (Inner Mongolia)": "呼伦贝尔（内蒙古）",
    "Jiuzhaigou": "九寨沟",
    "Huangshan (Yellow Mountain)": "黄山",
    "Emeishan + Leshan": "峨眉山+乐山",
    "Xishuangbanna": "西双版纳",
    "Sichuan Jiuzhaigou": "四川九寨沟",
    "Nagano/Japanese Alps (Japan)": "长野/日本阿尔卑斯（日本）",
    "Nepal (Kathmandu/Pokhara)": "尼泊尔（加德满都/博卡拉）",
    "Xi'an": "西安",
    "Chongqing": "重庆",
    "Beijing": "北京",
    "Changsha": "长沙",
    "Nanjing": "南京",
    "Hangzhou": "杭州",
    "Wuhan": "武汉",
    "Shenzhen": "深圳",
    "Guangzhou": "广州",
    "Hong Kong": "香港",
    "Dali/Lijiang (Yunnan)": "大理/丽江（云南）",
    "Water Towns (Xitang/Wuzhen)": "水乡（西塘/乌镇）",
    "Luang Prabang (Laos)": "琅勃拉邦（老挝）",
    "Pingyao Ancient City": "平遥古城",
    "Hoi An (Vietnam)": "会安（越南）",
    "Chengdu + Sichuan": "成都+四川",
    "Shunde (Guangdong)": "顺德（广东）",
    "Bangkok (Thailand)": "曼谷（泰国）",
    "Penang (Malaysia)": "槟城（马来西亚）",
    "Osaka (Japan)": "大阪（日本）",
    "Tokyo (Japan)": "东京（日本）",
    "Sabah (Malaysia)": "沙巴（马来西亚）",
    "Langkawi (Malaysia)": "兰卡威（马来西亚）",
    "El Nido (Philippines)": "爱妮岛（菲律宾）",
    "Sihanoukville/Koh Rong (Cambodia)": "西哈努克/高龙岛（柬埔寨）",
    "Chiang Mai (Thailand)": "清迈（泰国）",
    "Hanoi/Ha Long Bay (Vietnam)": "河内/下龙湾（越南）",
    "Siem Reap/Angkor (Cambodia)": "暹粒/吴哥窟（柬埔寨）",
    "Kyoto (Japan)": "京都（日本）",
    "Seoul (South Korea)": "首尔（韩国）",
    "Kanas Lake (Xinjiang)": "喀纳斯湖（新疆）",
    "Zhangye Danxia (Gansu)": "张掖丹霞（甘肃）",

    "烟台": "烟台",
    "大同": "大同",
    "沈阳": "沈阳",
    "泉州": "泉州",
    "兰州": "兰州",
    "大连": "大连",
    "南昌": "南昌",
    "郑州": "郑州",
    "济南": "济南",
    "合肥": "合肥",
    "福州": "福州",
    "洛阳": "洛阳",
    "哈尔滨": "哈尔滨",
    "漳州": "漳州",
    "太原": "太原",
    "长春": "长春",
    "宜昌": "宜昌",
    "南宁": "南宁",
    "秦皇岛": "秦皇岛",
    "赣州": "赣州",
    "九江": "九江",
    "威海": "威海",
    "开封": "开封",
    "焦作": "焦作",
    "泰安": "泰安",
    "湘西": "湘西",
    "恩施": "恩施",
    "海口": "海口",
    "柳州": "柳州",
    "保定": "保定",
    "襄阳": "襄阳",
    "芜湖": "芜湖",
    "十堰": "十堰",
    "景德镇": "景德镇",
    "黔东南": "黔东南",
    "汉中": "汉中",
    "上饶": "上饶",
    "宝鸡": "宝鸡",
    "岳阳": "岳阳",
    "衡阳": "衡阳",
    "万宁": "万宁",
    "南平": "南平",
    "红河": "红河",
    "迪庆": "迪庆",
    "湘潭": "湘潭",
    "安庆": "安庆",
    "延边": "延边",
    "陵水": "陵水",
    "丹东": "丹东",
    "晋中": "晋中",
    "宁德": "宁德",
    "承德": "承德",
    "敦煌": "敦煌",
    "牡丹江": "牡丹江",
    "丽水": "丽水",
    "南通": "南通",
    "台州": "台州",
    "嘉兴": "嘉兴",
    "宁波": "宁波",
    "常州": "常州",
    "徐州": "徐州",
    "扬州": "扬州",
    "温州": "温州",
    "湖州": "湖州",
    "绍兴": "绍兴",
    "苏州": "苏州",
    "金华": "金华",
    "镇江": "镇江",
}
